# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bflow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bflow.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x62\x66low.proto\"i\n\rMacTableQuery\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12&\n\tQueryType\x18\x02 \x01(\x0e\x32\x13.MacTableQuery.type\" \n\x04type\x12\n\n\x06NORMAL\x10\x00\x12\x0c\n\x08\x44\x45TAILED\x10\x01\":\n\rMacTableEntry\x12\x0e\n\x06switch\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0b\n\x03mac\x18\x03 \x01(\t2?\n\nTableQuery\x12\x31\n\x0bGetMacTable\x12\x0e.MacTableQuery\x1a\x0e.MacTableEntry\"\x00\x30\x01\x62\x06proto3')
)



_MACTABLEQUERY_TYPE = _descriptor.EnumDescriptor(
  name='type',
  full_name='MacTableQuery.type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DETAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=88,
  serialized_end=120,
)
_sym_db.RegisterEnumDescriptor(_MACTABLEQUERY_TYPE)


_MACTABLEQUERY = _descriptor.Descriptor(
  name='MacTableQuery',
  full_name='MacTableQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='MacTableQuery.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QueryType', full_name='MacTableQuery.QueryType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MACTABLEQUERY_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=120,
)


_MACTABLEENTRY = _descriptor.Descriptor(
  name='MacTableEntry',
  full_name='MacTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch', full_name='MacTableEntry.switch', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='MacTableEntry.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac', full_name='MacTableEntry.mac', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=180,
)

_MACTABLEQUERY.fields_by_name['QueryType'].enum_type = _MACTABLEQUERY_TYPE
_MACTABLEQUERY_TYPE.containing_type = _MACTABLEQUERY
DESCRIPTOR.message_types_by_name['MacTableQuery'] = _MACTABLEQUERY
DESCRIPTOR.message_types_by_name['MacTableEntry'] = _MACTABLEENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MacTableQuery = _reflection.GeneratedProtocolMessageType('MacTableQuery', (_message.Message,), dict(
  DESCRIPTOR = _MACTABLEQUERY,
  __module__ = 'bflow_pb2'
  # @@protoc_insertion_point(class_scope:MacTableQuery)
  ))
_sym_db.RegisterMessage(MacTableQuery)

MacTableEntry = _reflection.GeneratedProtocolMessageType('MacTableEntry', (_message.Message,), dict(
  DESCRIPTOR = _MACTABLEENTRY,
  __module__ = 'bflow_pb2'
  # @@protoc_insertion_point(class_scope:MacTableEntry)
  ))
_sym_db.RegisterMessage(MacTableEntry)



_TABLEQUERY = _descriptor.ServiceDescriptor(
  name='TableQuery',
  full_name='TableQuery',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=182,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMacTable',
    full_name='TableQuery.GetMacTable',
    index=0,
    containing_service=None,
    input_type=_MACTABLEQUERY,
    output_type=_MACTABLEENTRY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLEQUERY)

DESCRIPTOR.services_by_name['TableQuery'] = _TABLEQUERY

# @@protoc_insertion_point(module_scope)
