# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bflow_pb2 as bflow__pb2


class TableQueryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMacTable = channel.unary_stream(
        '/TableQuery/GetMacTable',
        request_serializer=bflow__pb2.MacTableQuery.SerializeToString,
        response_deserializer=bflow__pb2.MacTableEntry.FromString,
        )


class TableQueryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMacTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TableQueryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMacTable': grpc.unary_stream_rpc_method_handler(
          servicer.GetMacTable,
          request_deserializer=bflow__pb2.MacTableQuery.FromString,
          response_serializer=bflow__pb2.MacTableEntry.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TableQuery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
